- targets:
    - azwu2nbca001.bh.bozemanhealth.org:9182
    - azwu2nbca002.bh.bozemanhealth.org:9182
    - azwu2nbcaw001.bh.bozemanhealth.org:9182
    - azwu2ncab001.bh.bozemanhealth.org:9182
    - azwu2nce001.bh.bozemanhealth.org:9182
    - azwu2nce002.bh.bozemanhealth.org:9182
    - azwu2nce003.bh.bozemanhealth.org:9182
    - azwu2nce004.bh.bozemanhealth.org:9182
    - azwu2ncepx001.bh.bozemanhealth.org:9182
    - azwu2ncepx002.bh.bozemanhealth.org:9182
    - azwu2nclar001.bh.bozemanhealth.org:9182
    - azwu2nclarc001.bh.bozemanhealth.org:9182
    - azwu2ncube001.bh.bozemanhealth.org:9182
    - azwu2ndss001.bh.bozemanhealth.org:9182
    - azwu2ndss002.bh.bozemanhealth.org:9182
    - azwu2necl001.bh.bozemanhealth.org:9182
    - azwu2necl002.bh.bozemanhealth.org:9182
    - azwu2necl003.bh.bozemanhealth.org:9182
    - azwu2necl004.bh.bozemanhealth.org:9182
    - azwu2neps001.bh.bozemanhealth.org:9182
    - azwu2neps002.bh.bozemanhealth.org:9182
    - azwu2nhsw001.bh.bozemanhealth.org:9182
    - azwu2nhsw002.bh.bozemanhealth.org:9182
    - azwu2nhsw003.bh.bozemanhealth.org:9182
    - azwu2nhsw004.bh.bozemanhealth.org:9182
    - azwu2nhswe001.bh.bozemanhealth.org:9182
    - azwu2nhswe002.bh.bozemanhealth.org:9182
    - azwu2nicbg001.bh.bozemanhealth.org:9182
    - azwu2nicbg002.bh.bozemanhealth.org:9182
    - azwu2nicbg003.bh.bozemanhealth.org:9182
    - azwu2nicfg001.bh.bozemanhealth.org:9182
    - azwu2nicfg002.bh.bozemanhealth.org:9182
    - azwu2nicfg003.bh.bozemanhealth.org:9182
    - azwu2nmyc001.bh.bozemanhealth.org:9182
    - azwu2nmyc002.bh.bozemanhealth.org:9182
    - azwu2nmyc003.bh.bozemanhealth.org:9182
    - azwu2nmyc004.bh.bozemanhealth.org:9182
    - azwu2nrpx001.bh.bozemanhealth.org:9182
    - azwu2nrpx002.bh.bozemanhealth.org:9182
    - azwu2nslic001.bh.bozemanhealth.org:9182
    - azwu2nslic002.bh.bozemanhealth.org:9182
    - azwu2nwbs001.bh.bozemanhealth.org:9182
    - azwu2nwbs002.bh.bozemanhealth.org:9182
    - azwu2nwbs003.bh.bozemanhealth.org:9182
    - azwu2nwbs004.bh.bozemanhealth.org:9182
  labels:
    customer: Bozeman
